version: '3.8'

services:
  api:
    build:
      context: ./API
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    networks:
      - my-network
    environment:
      - NODE_ENV=production

  client:
    build:
      context: ./Client
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    networks:
      - my-network
    depends_on:
      - api

networks:
  my-network:
    driver: bridge
